#!/usr/bin/env python
"""Validate the gridded field export — docs/data/fields/** and the manifest.

    conda run -n earth2 python scripts/check_fields.py

The gate that makes the encoding trustworthy is layer 3: **every emitted PNG is
decoded back to float through the scale published in `manifest.json` and
compared against the source array, and the maximum absolute difference must be
at most half the quantization step.** Nothing else here can substitute for it.
A scale that is stale, mistyped, off by a factor, or simply attached to the
wrong lead produces a PNG that renders as a perfectly plausible weather map of
the wrong numbers, and the only way to notice is to invert the encoding and
check.

Five layers, mirroring scripts/check_export.py's structure and reusing its
schema validator:

1. **Schema.** `manifest.json` against `docs/data/schema/manifest.schema.json`,
   and every `fields/<init>/index.json` sidecar against that schema's
   `$defs/fieldsInit` — the sidecar and the manifest entry are the same object,
   so one definition governs both.
2. **Structure.** The manifest's `fields` section, the sidecars, and the files
   on disk must agree: which inits exist, which PNGs exist, their dimensions,
   the byte totals, and — the E4-specific invariants — that error scales are
   symmetric about zero, that the reserved missing byte sits outside the data
   range, and that a lead marked `truth_pending` has no PNG while every lead
   marked `ok` has one.
3. **The decode gate**, above. Source arrays are regenerated by calling
   `scoreboard.fields` itself, so the gate tests the pipeline rather than a
   second copy of it. It runs for every init whose forecast zarr survives; an
   init whose zarr sweep.py has purged is reported as unverifiable, and the run
   **fails if no init could be verified at all**, so the gate cannot decay into
   a no-op as retention rolls forward.
4. **Staleness.** A real-time init exported the day it ran has error fields for
   only its first leads. There is no top-up for fields — a re-export is a full
   one — so unless something insists, the map's error view stays frozen at 2 of
   5 leads until the zarr is swept and it can never be completed at all.
5. **The gate itself.** A synthetic tree, corrupted one way at a time, with each
   corruption required to be caught, and schema mutations required to be
   rejected. A check that accepted everything would otherwise look exactly like
   a passing one — and the half-step assertion in particular is easy to write in
   a form that can never fail.
"""

import contextlib
import copy
import io
import json
import shutil
import sys
import tempfile
from datetime import datetime, timedelta
from pathlib import Path

import numpy as np
import yaml

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
sys.path.insert(0, str(_HERE.parent))

import check_export  # noqa: E402  — schema validator, shared deliberately
from scoreboard import export, fields  # noqa: E402

schema_errors = check_export.schema_errors

# Fields are re-exported wholesale, not topped up, so a real-time init has to be
# revisited while its zarr survives. One lead step of slack covers the case
# where the availability boundary moved between the export and this check.
TRUTH_STALENESS_GRACE_HOURS = 6

# PLAN_EXPLORER.md §4's per-init budget for the eventual four-variable export at
# 0.5°. t2m alone is a quarter of it (§4, "Note this table is the *eventual*
# four-variable budget"), and the current export is 1.0°, so this is a ceiling
# that should be nowhere near hit — it exists to make a resolution or lead-count
# change that blows the repo-growth budget (§7) fail here rather than in git.
FIELDS_BUDGET_BYTES = 24 * 1024 * 1024


def subschema(manifest_schema: dict, name: str) -> dict:
    """A `$defs` entry, wrapped so its internal `$ref`s still resolve.

    The sidecar files are the manifest's `fields` values, so they are validated
    against the same definition rather than a second schema that could drift
    from it. Both the local validator and jsonschema resolve `#/$defs/...`
    against the document root, hence carrying `$defs` along.
    """
    return {"$ref": f"#/$defs/{name}", "$defs": manifest_schema["$defs"]}


# ---------------------------------------------------------------------------
# Layer 3: the decode gate


def encoding_errors(label: str, codes: np.ndarray, source: np.ndarray,
                    scale) -> list[str]:
    """Decode `codes` through `scale` and compare against `source`.

    Three separate claims, because they fail independently:

    - the decoded field is within **half a quantization step** of the source
      everywhere. Round-to-nearest over a scale that contains the data makes
      this an equality bound, not a heuristic one, so exceeding it means the
      scale is not the one the field was encoded with;
    - the reserved missing byte appears at exactly the cells where the source is
      non-finite, and nowhere else — a renderer draws those transparent, so a
      misplaced one silently erases data or paints a hole as a temperature;
    - the shapes match, which catches a transposed or wrongly-regridded field
      before the value comparison reports something incomprehensible.
    """
    errs = []
    if codes.shape != source.shape:
        return [f"{label}: PNG is {codes.shape}, source array is {source.shape}"]

    finite = np.isfinite(source)
    missing = codes == fields.MISSING_BYTE
    if int((missing & finite).sum()):
        n = int((missing & finite).sum())
        errs.append(f"{label}: {n} cell(s) carry the reserved missing byte "
                    f"({fields.MISSING_BYTE}) where the source is finite — that "
                    "data would be drawn as transparent")
    if int((~missing & ~finite).sum()):
        n = int((~missing & ~finite).sum())
        errs.append(f"{label}: {n} non-finite source cell(s) were encoded as "
                    "data rather than the reserved missing byte")

    both = finite & ~missing
    if not both.any():
        return errs
    decoded = fields.dequantize(codes, scale)
    step = fields.quantization_step(scale)
    resid = np.abs(decoded[both] - source[both])
    worst = float(resid.max())
    # Strictly the bound is step/2; the tolerance covers only the float64
    # rounding of the comparison itself, and is ~10 orders of magnitude below a
    # quantization step, so it cannot absorb a real encoding fault.
    if worst > 0.5 * step * (1 + 1e-9) + 1e-12:
        i = int(np.argmax(resid))
        errs.append(
            f"{label}: max |decoded - source| = {worst:.6g} exceeds half the "
            f"quantization step ({0.5 * step:.6g}; scale {list(scale)}, "
            f"{fields.LEVELS} levels). Worst cell: source "
            f"{source[both][i]:.6g}, decoded {decoded[both][i]:.6g}. The PNG "
            "was not encoded with the scale the manifest publishes.")
    return errs


def source_lookup_for_init(cfg: dict, entry: dict, init_time: datetime):
    """A (model, var, kind, lead) -> array callable, or None if unverifiable.

    Regenerates the source arrays with `scoreboard.fields` itself, at the leads
    the export marked `ok` rather than the leads the clock now permits — a
    real-time init's truth window advances between the export and this run, and
    the gate must reproduce what was encoded, not what could be encoded today.
    """
    data = Path(cfg["paths"]["data"])
    models = [m for m in entry["models"]
              if fields.forecast_path(data, m, init_time).exists()]
    if not models:
        return None, entry["models"]
    variables = sorted(entry["variables"])
    leads = entry["leads"]

    ok_leads = sorted({int(h)
                       for v in entry["variables"].values()
                       for h, st in v["error"]["status"].items()
                       if st == export.STATUS_OK})
    truth_da = None
    if ok_leads:
        truth_da, _ = fields.fetch_truth_at(cfg, init_time, ok_leads, variables)

    res = entry["grid"]["resolution_deg"]
    cache: dict = {}

    def lookup(model, var, kind, lead):
        if model not in models:
            return None
        if model not in cache:
            cache[model] = fields.source_arrays(cfg, init_time, model, variables,
                                                leads, res, truth_da, ok_leads)
        return cache[model].get((var, kind, lead))

    return lookup, [m for m in entry["models"] if m not in models]


# ---------------------------------------------------------------------------
# Layers 2 + 3 over one init entry


def check_init_entry(name: str, entry: dict, root: Path,
                     lookup) -> tuple[list[str], int]:
    """Structure, encoding invariants, and the decode gate. (errors, n decoded).

    `lookup(model, var, kind, lead) -> array | None` supplies source arrays;
    None means unverifiable (the forecast zarr is gone), which is reported by
    the caller rather than treated as a pass.
    """
    errs: list[str] = []
    n_decoded = 0
    d = root / entry["dir"]
    if d.name != name:
        errs.append(f"fields[{name}]: dir {entry['dir']!r} does not end in the "
                    "init stamp it is keyed by")
    if not d.is_dir():
        return errs + [f"fields[{name}]: {d} does not exist"], 0

    enc = entry["encoding"]
    if enc["levels"] != enc["max_byte"] - enc["min_byte"]:
        errs.append(f"fields[{name}]: encoding levels {enc['levels']} != "
                    f"max_byte - min_byte ({enc['max_byte']} - "
                    f"{enc['min_byte']})")
    if enc["min_byte"] <= enc["missing"] <= enc["max_byte"]:
        errs.append(f"fields[{name}]: the reserved missing byte "
                    f"{enc['missing']} lies inside the data range "
                    f"[{enc['min_byte']}, {enc['max_byte']}] — a real value and "
                    "'no data' would encode identically")
    for key, want in (("missing", fields.MISSING_BYTE),
                      ("min_byte", fields.MIN_BYTE),
                      ("max_byte", fields.MAX_BYTE),
                      ("levels", fields.LEVELS)):
        if enc[key] != want:
            errs.append(f"fields[{name}]: encoding.{key} is {enc[key]} but "
                        f"scoreboard.fields encodes with {want}")

    grid = entry["grid"]
    shape = (grid["height"], grid["width"])
    if grid["lat_step"] >= 0:
        errs.append(f"fields[{name}]: lat_step {grid['lat_step']} is not "
                    "negative — the exported grid runs north to south, and a "
                    "renderer trusting this would draw it upside down")
    for axis, start, step, n, span in (
            ("lat", grid["lat_start"], grid["lat_step"], grid["height"], -180.0),
            ("lon", grid["lon_start"], grid["lon_step"], grid["width"], 360.0)):
        covered = step * (n - 1 if axis == "lat" else n)
        if abs(covered - span) > 1e-9:
            errs.append(f"fields[{name}]: {axis} runs {start} by {step} for {n} "
                        f"cells, covering {covered}° rather than {span}°")

    seen: set[Path] = set()
    for var, vmeta in entry["variables"].items():
        for kind, meta in (("forecast", vmeta["forecast"]),
                           ("error", vmeta["error"])):
            scales = meta["scales"]
            status = meta.get("status")
            for h in entry["leads"]:
                key = str(h)
                pending = status is not None and \
                    status.get(key) == export.STATUS_TRUTH_PENDING
                if status is not None and key not in status:
                    errs.append(f"fields[{name}] {var}.{kind}: lead {h} h has no "
                                "status")
                if pending:
                    if key in scales:
                        errs.append(f"fields[{name}] {var}.{kind}: lead {h} h is "
                                    f"{export.STATUS_TRUTH_PENDING} but carries "
                                    "a scale")
                    continue
                if key not in scales:
                    errs.append(f"fields[{name}] {var}.{kind}: lead {h} h has no "
                                "scale in the manifest — it cannot be decoded")
                    continue
                lo, hi = scales[key]
                if not (lo < hi):
                    errs.append(f"fields[{name}] {var}.{kind} lead {h} h: scale "
                                f"[{lo}, {hi}] is not increasing")
                if kind == "error" and lo != -hi:
                    # Exact equality, not a tolerance: the scale is built by
                    # negating one magnitude, so anything else means it was not.
                    errs.append(f"fields[{name}] {var}.error lead {h} h: scale "
                                f"[{lo}, {hi}] is not symmetric about zero — a "
                                "diverging ramp built from it would put its "
                                "neutral colour at "
                                f"{0.5 * (lo + hi):.6g}, misrepresenting the "
                                "sign of a bias")

    for model in entry["models"]:
        for var, vmeta in entry["variables"].items():
            for kind, meta in (("forecast", vmeta["forecast"]),
                               ("error", vmeta["error"])):
                status = meta.get("status")
                for h in entry["leads"]:
                    key = str(h)
                    path = d / model / var / meta["file"].replace("{lead}", key)
                    pending = status is not None and \
                        status.get(key) == export.STATUS_TRUTH_PENDING
                    if pending:
                        if path.exists():
                            errs.append(
                                f"{path.relative_to(root)}: exists although "
                                f"{var}.{kind} lead {h} h is marked "
                                f"{export.STATUS_TRUTH_PENDING}")
                        continue
                    if not path.exists():
                        errs.append(f"fields[{name}]: {path.relative_to(root)} "
                                    f"is missing, but {var}.{kind} lead {h} h is "
                                    f"marked {export.STATUS_OK}")
                        continue
                    seen.add(path)
                    if key not in meta["scales"]:
                        continue
                    codes = fields.read_png(path)
                    if codes.shape != shape:
                        errs.append(f"{path.relative_to(root)}: {codes.shape} "
                                    f"does not match the declared grid {shape}")
                        continue
                    bad = np.unique(codes[(codes != enc["missing"])
                                          & ((codes < enc["min_byte"])
                                             | (codes > enc["max_byte"]))])
                    if bad.size:
                        errs.append(f"{path.relative_to(root)}: byte value(s) "
                                    f"{bad.tolist()} are neither the missing "
                                    "value nor inside the data range")
                    src = lookup(model, var, kind, h) if lookup else None
                    if src is None:
                        continue
                    errs += encoding_errors(str(path.relative_to(root)), codes,
                                            src, meta["scales"][key])
                    n_decoded += 1

    on_disk = {p for p in d.rglob("*.png")}
    orphans = sorted(str(p.relative_to(root)) for p in on_disk - seen)
    if orphans:
        errs.append(f"fields[{name}]: {len(orphans)} PNG(s) on disk that the "
                    f"manifest does not describe — {orphans[:4]}")
    if len(on_disk) != entry["png_count"]:
        errs.append(f"fields[{name}]: png_count {entry['png_count']} != "
                    f"{len(on_disk)} file(s) on disk")
    want_complete = (len(entry["models"]) * len(entry["variables"])
                     * len(entry["leads"]) * 2)
    if entry["png_count_when_complete"] != want_complete:
        errs.append(f"fields[{name}]: png_count_when_complete "
                    f"{entry['png_count_when_complete']} != models x variables "
                    f"x leads x 2 = {want_complete}")
    nbytes = sum(p.stat().st_size for p in on_disk)
    if nbytes != entry["bytes"]:
        errs.append(f"fields[{name}]: bytes {entry['bytes']} != actual {nbytes}")
    if nbytes > FIELDS_BUDGET_BYTES:
        errs.append(f"fields[{name}]: {nbytes / 1048576:.1f} MiB exceeds the "
                    f"{FIELDS_BUDGET_BYTES / 1048576:.0f} MiB per-init budget "
                    "(PLAN_EXPLORER.md §4/§7)")
    return errs, n_decoded


def staleness_errors(name: str, entry: dict, now: datetime) -> list[str]:
    """A lead whose truth has landed but whose error field was never written.

    Unlike points, fields have no incremental top-up: the fix is a full
    re-export, which is only possible while the forecast zarr survives. So an
    init left alone after its first export keeps an error map that stops at
    lead 48 h for the rest of its life.
    """
    errs = []
    init = datetime.strptime(entry["init_time"], export.TIME_FMT)
    leads = entry["leads"]
    through = export.truth_available_through(init, leads, entry["regime"], now)
    if through is None:
        return errs
    cutoff = through - timedelta(hours=TRUTH_STALENESS_GRACE_HOURS)
    for var, vmeta in entry["variables"].items():
        stale = [h for h in leads
                 if vmeta["error"]["status"].get(str(h)) == export.STATUS_TRUTH_PENDING
                 and init + timedelta(hours=h) <= cutoff]
        if stale:
            errs.append(
                f"fields[{name}] {var}: lead(s) {stale} h are marked "
                f"{export.STATUS_TRUTH_PENDING}, but their truth has been "
                f"available since at or before {cutoff:{export.TIME_FMT}}. "
                "Fields are re-exported, not topped up — re-run `python -m "
                f"scoreboard.fields --init {name}` while the forecast zarr "
                "still exists.")
    return errs


def check_tree(root: Path, cfg: dict, manifest_schema: dict, now: datetime,
               source_for=None) -> tuple[list[str], dict]:
    """Layers 1-4 over one docs/data tree. Returns (failures, stats).

    Parameterized by root, cfg, clock and source provider so layer 5 can run the
    identical checks against a synthetic tree. A gate that only ever ran against
    the real tree could not be shown to reject anything.
    """
    failures: list[str] = []
    mpath = root / "manifest.json"
    if not mpath.exists():
        return [f"{mpath} does not exist — run `python -m scoreboard.export`"], {}
    try:
        manifest = json.loads(mpath.read_text())
    except json.JSONDecodeError as e:
        return [f"manifest.json is not valid JSON ({e})"], {}

    bad = schema_errors(manifest, manifest_schema)
    failures += [f"manifest.json {m}" for m in bad]
    if bad:
        return failures, {}

    fields_root = root / "fields"
    dirs = sorted(d.name for d in fields_root.glob("*")
                  if d.is_dir()) if fields_root.exists() else []
    section = manifest["fields"]
    if sorted(section) != dirs:
        failures.append(f"manifest.json: fields lists {sorted(section)} but "
                        f"fields/ holds {dirs}")

    entry_schema = subschema(manifest_schema, "fieldsInit")
    stats = {"n_png": 0, "n_decoded": 0, "unverified": [], "inits": [],
             "bytes": {}}
    for name in sorted(set(section) & set(dirs)):
        entry = section[name]
        # The sidecar is the durable record; the manifest is aggregated from it.
        # They are the same object, so any difference means one of the two was
        # written by something other than the exporter.
        sidecar_path = fields_root / name / "index.json"
        if not sidecar_path.exists():
            failures.append(f"fields[{name}]: no index.json sidecar — the "
                            "manifest's copy cannot be regenerated, and "
                            "`python -m scoreboard.export` would drop this init")
        else:
            sidecar = json.loads(sidecar_path.read_text())
            failures += [f"fields/{name}/index.json {m}"
                         for m in schema_errors(sidecar, entry_schema)]
            if sidecar != entry:
                failures.append(
                    f"fields[{name}]: manifest.json and "
                    f"fields/{name}/index.json disagree. The manifest is "
                    "aggregated from the sidecar by export.write_manifest, so "
                    "one of them was hand-edited or an export was interrupted; "
                    "re-run `python -m scoreboard.export`.")
        entry_bad = schema_errors(entry, entry_schema)
        failures += [f"manifest.json fields[{name}] {m}" for m in entry_bad]
        if entry_bad:
            continue

        lookup, gone = (source_for(name, entry) if source_for else (None, []))
        errs, n_dec = check_init_entry(name, entry, root, lookup)
        failures += errs
        failures += staleness_errors(name, entry, now)
        stats["n_decoded"] += n_dec
        stats["n_png"] += entry["png_count"]
        stats["bytes"][name] = entry["bytes"]
        stats["inits"].append(entry)
        if gone:
            stats["unverified"].append((name, gone))
    return failures, stats


def real_source_provider(cfg: dict):
    def provide(name: str, entry: dict):
        init = datetime.strptime(entry["init_time"], export.TIME_FMT)
        return source_lookup_for_init(cfg, entry, init)
    return provide


# ---------------------------------------------------------------------------
# Layer 5: prove the gate rejects a corrupted export
#
# Synthetic fields, so the self-test runs with no zarrs, no network and no GPU:
# a smooth analytic "forecast" and a smaller analytic "error", plus a patch of
# NaN so the reserved missing byte is exercised rather than assumed.

SYNTH_NOW = datetime(2026, 7, 30, 12)
SYNTH_INIT = datetime(2023, 1, 15, 0)        # historic: truth is complete
SYNTH_NAME = f"{SYNTH_INIT:{export.INIT_FMT}}"
SYNTH_LEADS = [24, 48]
SYNTH_MODELS = ["aurora", "atlas"]
SYNTH_RES = 10.0                             # 19 x 36 — small and fast


def _synth_source(model: str, kind: str, lead: int) -> np.ndarray:
    lat, lon = fields.target_grid(SYNTH_RES)
    la = lat[:, None]
    lo = lon[None, :]
    seed = SYNTH_MODELS.index(model) + lead / 24.0
    if kind == "forecast":
        # Asymmetric in latitude on purpose: a field built only from
        # cos(lat) survives a north-south flip unchanged, which would make
        # the orientation corruption below untestable.
        f = (288.0 + 30.0 * np.cos(np.deg2rad(la)) + 0.25 * la
             + 3.0 * np.sin(np.deg2rad(lo) + seed))
    else:
        f = 2.5 * np.sin(np.deg2rad(2 * la)) * np.cos(np.deg2rad(lo) - seed)
    f = np.broadcast_to(f, (lat.size, lon.size)).astype(np.float64).copy()
    f[0, :3] = np.nan            # a hole, so MISSING_BYTE is really exercised
    return f


def _synth_arrays() -> dict:
    return {(m, "t2m", k, h): _synth_source(m, k, h)
            for m in SYNTH_MODELS for k in ("forecast", "error")
            for h in SYNTH_LEADS}


def _synth_site(site: Path) -> dict:
    """Materialize a pristine, passing tree under `site`. Returns its cfg."""
    arrays = _synth_arrays()
    lat, lon = fields.target_grid(SYNTH_RES)
    root = site / "data"
    d = root / "fields" / SYNTH_NAME
    scales = {}
    for kind in ("forecast", "error"):
        for h in SYNTH_LEADS:
            group = [arrays[(m, "t2m", kind, h)] for m in SYNTH_MODELS]
            scales[(kind, h)] = (fields.forecast_scale(group) if kind == "forecast"
                                 else fields.error_scale(group))
    for m in SYNTH_MODELS:
        for kind in ("forecast", "error"):
            for h in SYNTH_LEADS:
                fields.write_png(
                    d / m / "t2m" / f"{'f' if kind == 'forecast' else 'e'}{h}.png",
                    fields.quantize(arrays[(m, "t2m", kind, h)], scales[(kind, h)]))
    entry = {
        "schema_version": 1,
        "init_time": f"{SYNTH_INIT:{export.TIME_FMT}}",
        "generated": f"{SYNTH_NOW:{export.TIME_FMT}}",
        "regime": "historic", "tier": "final",
        "init_source": "era5_arco", "truth_source": "era5_arco",
        "dir": f"fields/{SYNTH_NAME}",
        "grid": {"resolution_deg": SYNTH_RES, "width": int(lon.size),
                 "height": int(lat.size), "lat_start": 90.0, "lat_step": -SYNTH_RES,
                 "lon_start": 0.0, "lon_step": SYNTH_RES},
        "encoding": {"dtype": "uint8", "missing": fields.MISSING_BYTE,
                     "min_byte": fields.MIN_BYTE, "max_byte": fields.MAX_BYTE,
                     "levels": fields.LEVELS, "decode": "value = scale[0] + ..."},
        "leads": list(SYNTH_LEADS),
        "models": list(SYNTH_MODELS),
        "models_expected": list(SYNTH_MODELS),
        "variables": {"t2m": {
            "units": "K",
            "forecast": {"file": "f{lead}.png",
                         "scales": {str(h): scales[("forecast", h)]
                                    for h in SYNTH_LEADS}},
            "error": {"file": "e{lead}.png", "symmetric": True,
                      "definition": "model - truth", "truth_source": "era5_arco",
                      "scales": {str(h): scales[("error", h)] for h in SYNTH_LEADS},
                      "status": {str(h): "ok" for h in SYNTH_LEADS}},
        }},
        "png_count": len(SYNTH_MODELS) * len(SYNTH_LEADS) * 2,
        "png_count_when_complete": len(SYNTH_MODELS) * len(SYNTH_LEADS) * 2,
        "bytes": sum(p.stat().st_size for p in d.rglob("*.png")),
    }
    (d / "index.json").write_text(json.dumps(entry, indent=1) + "\n")
    manifest = {
        "schema_version": 1,
        "generated": f"{SYNTH_NOW:{export.TIME_FMT}}",
        "series_statuses": ["ok", "no_variable", "truth_pending", "unavailable"],
        "leads": list(SYNTH_LEADS),
        "variables": {"t2m": {"label": "2 m temperature", "units": "K",
                              "kind": "state", "decimals": 2}},
        "cities": [{"id": "alphaville", "name": "Alphaville", "lat": 10.0,
                    "lon": 20.0}],
        "inits": [],
        "fields": {SYNTH_NAME: copy.deepcopy(entry)},
    }
    (root / "manifest.json").write_text(json.dumps(manifest, indent=1) + "\n")
    return {"paths": {"data": str(site / "store"), "site": str(site)},
            "historic_cutoff_days": 120, "retention_days": 30}


def _synth_provider(name: str, entry: dict):
    arrays = _synth_arrays()

    def lookup(model, var, kind, lead):
        return arrays.get((model, var, kind, lead))
    return lookup, []


def _edit(site: Path, mutate, sidecar: bool = True) -> None:
    """Apply `mutate` to the manifest entry and, unless told otherwise, to the
    sidecar too — so the corruption is internally consistent and can only be
    caught by decoding, not by cross-referencing the two copies."""
    root = site / "data"
    m = json.loads((root / "manifest.json").read_text())
    mutate(m["fields"][SYNTH_NAME])
    (root / "manifest.json").write_text(json.dumps(m, indent=1) + "\n")
    if sidecar:
        p = root / "fields" / SYNTH_NAME / "index.json"
        s = json.loads(p.read_text())
        mutate(s)
        p.write_text(json.dumps(s, indent=1) + "\n")


def _png(site: Path, model: str, kind: str, lead: int) -> Path:
    return (site / "data" / "fields" / SYNTH_NAME / model / "t2m"
            / f"{'f' if kind == 'forecast' else 'e'}{lead}.png")


def _rewrite_png(site: Path, model: str, kind: str, lead: int, transform) -> None:
    p = _png(site, model, kind, lead)
    codes = fields.read_png(p)
    fields.write_png(p, transform(codes))
    _refresh_bytes(site)


def _refresh_bytes(site: Path) -> None:
    """Reconcile the byte totals, leaving everything else as corrupted.

    The byte count is the one thing a hand-edited tree obviously breaks, so a
    check that reconciles it and stops there would pass every case below.
    """
    d = site / "data" / "fields" / SYNTH_NAME
    n = sum(p.stat().st_size for p in d.rglob("*.png"))
    _edit(site, lambda e: e.update(bytes=n))


def _swap_scales(entry: dict) -> None:
    """Attach each of two leads' scales to the other's PNGs."""
    s = entry["variables"]["t2m"]["forecast"]["scales"]
    s["24"], s["48"] = s["48"], s["24"]


def _shift_scale(entry: dict, kind: str, lead: int, by: float) -> None:
    s = entry["variables"]["t2m"][kind]["scales"][str(lead)]
    entry["variables"]["t2m"][kind]["scales"][str(lead)] = [s[0] + by, s[1] + by]


# (description, corruption). Each must make check_tree report a failure. These
# are the shapes a wrong encoding actually takes — every one is schema-valid and
# most leave the manifest and the sidecar in perfect agreement.
TREE_CORRUPTIONS = [
    # The decode gate proper: a scale that no longer matches the encoding.
    ("a forecast scale shifted by half a kelvin",
     lambda s: _edit(s, lambda e: _shift_scale(e, "forecast", 24, 0.5))),
    ("a forecast scale widened",
     lambda s: _edit(s, lambda e: e["variables"]["t2m"]["forecast"]["scales"]
                     .__setitem__("24", [200.0, 340.0]))),
    ("two leads' scales swapped", lambda s: _edit(s, _swap_scales)),
    ("an error scale made asymmetric",
     lambda s: _edit(s, lambda e: e["variables"]["t2m"]["error"]["scales"]
                     .__setitem__("24", [-1.0, 3.0]))),
    ("an error scale symmetric but wrong",
     lambda s: _edit(s, lambda e: e["variables"]["t2m"]["error"]["scales"]
                     .__setitem__("24", [-9.0, 9.0]))),
    # The PNG itself, with the manifest left correct.
    ("a PNG flipped north-south",
     lambda s: _rewrite_png(s, "atlas", "forecast", 24, lambda c: c[::-1, :])),
    ("a PNG rolled half a turn in longitude",
     lambda s: _rewrite_png(s, "atlas", "forecast", 24,
                            lambda c: np.roll(c, c.shape[1] // 2, axis=1))),
    ("a single byte nudged by two levels",
     lambda s: _rewrite_png(s, "aurora", "error", 48, _nudge_one)),
    ("the missing-value hole painted over with data",
     lambda s: _rewrite_png(s, "aurora", "forecast", 24, _fill_missing)),
    ("a cell of real data replaced by the missing byte",
     lambda s: _rewrite_png(s, "aurora", "forecast", 24, _blank_one)),
    # Structure.
    ("a PNG deleted while its lead is still marked ok",
     lambda s: (_png(s, "atlas", "error", 48).unlink(), _refresh_bytes(s))),
    ("a lead marked truth_pending while its PNG is still on disk",
     lambda s: _edit(s, lambda e: e["variables"]["t2m"]["error"]["status"]
                     .__setitem__("48", "truth_pending"))),
    ("a lead marked ok with no scale",
     lambda s: _edit(s, lambda e: e["variables"]["t2m"]["error"]["scales"]
                     .pop("48"))),
    ("png_count no longer matching the files",
     lambda s: _edit(s, lambda e: e.update(png_count=e["png_count"] + 1))),
    ("byte total no longer matching the files",
     lambda s: _edit(s, lambda e: e.update(bytes=e["bytes"] + 1))),
    ("declared grid height off by one",
     lambda s: _edit(s, lambda e: e["grid"].update(height=e["grid"]["height"] + 1))),
    ("latitude declared ascending",
     lambda s: _edit(s, lambda e: e["grid"].update(lat_start=-90.0,
                                                   lat_step=SYNTH_RES))),
    ("the reserved missing byte moved inside the data range",
     lambda s: _edit(s, lambda e: e["encoding"].update(missing=128))),
    ("levels inconsistent with the byte range",
     lambda s: _edit(s, lambda e: e["encoding"].update(levels=255))),
    ("an orphan PNG the manifest does not describe",
     lambda s: (shutil.copy(_png(s, "atlas", "forecast", 24),
                            _png(s, "atlas", "forecast", 24).with_name("f999.png")),
                _refresh_bytes(s))),
    # The two copies of the same record drifting apart.
    ("manifest and sidecar disagreeing on a scale",
     lambda s: _edit(s, lambda e: _shift_scale(e, "forecast", 48, 0.5),
                     sidecar=False)),
    ("the sidecar deleted",
     lambda s: (s / "data" / "fields" / SYNTH_NAME / "index.json").unlink()),
    ("an init directory the manifest does not list",
     lambda s: (s / "data" / "fields" / "2026-07-28T00").mkdir(parents=True)),
]


def _nudge_one(codes: np.ndarray) -> np.ndarray:
    """Move one byte by two levels.

    Two rather than one: a one-level move can land a cell whose original
    residual sat at exactly -step/2 back on +step/2, i.e. still inside the
    bound, so a self-test built on it would pass or fail by luck.
    """
    out = codes.copy()
    r, c = out.shape[0] // 2, out.shape[1] // 2
    v = int(out[r, c])
    out[r, c] = np.uint8(v - 2 if v > fields.MIN_BYTE + 2 else v + 2)
    return out


def _fill_missing(codes: np.ndarray) -> np.ndarray:
    out = codes.copy()
    out[out == fields.MISSING_BYTE] = 128
    return out


def _blank_one(codes: np.ndarray) -> np.ndarray:
    out = codes.copy()
    out[out.shape[0] // 2, out.shape[1] // 2] = fields.MISSING_BYTE
    return out


# Schema mutations for the fields section. Layer 5's tree cases are all
# schema-valid by design, so without these nothing would prove the schema is
# doing any work at all.
FIELD_SCHEMA_MUTATIONS = [
    ("init keyed by something other than a stamp",
     lambda d: d["fields"].update(latest=d["fields"][SYNTH_NAME])),
    ("missing encoding block",
     lambda d: d["fields"][SYNTH_NAME].pop("encoding")),
    ("missing grid block", lambda d: d["fields"][SYNTH_NAME].pop("grid")),
    ("dir escaping fields/",
     lambda d: d["fields"][SYNTH_NAME].update(dir="../../etc")),
    ("dtype other than uint8",
     lambda d: d["fields"][SYNTH_NAME]["encoding"].update(dtype="uint16")),
    ("missing byte out of uint8 range",
     lambda d: d["fields"][SYNTH_NAME]["encoding"].update(missing=999)),
    ("error layer no longer claiming symmetry",
     lambda d: d["fields"][SYNTH_NAME]["variables"]["t2m"]["error"]
     .update(symmetric=False)),
    ("error definition rewritten",
     lambda d: d["fields"][SYNTH_NAME]["variables"]["t2m"]["error"]
     .update(definition="truth - model")),
    ("a scale with three numbers",
     lambda d: d["fields"][SYNTH_NAME]["variables"]["t2m"]["forecast"]["scales"]
     .update({"24": [1.0, 2.0, 3.0]})),
    ("a scale keyed by a non-numeric lead",
     lambda d: d["fields"][SYNTH_NAME]["variables"]["t2m"]["forecast"]["scales"]
     .update({"24h": [1.0, 2.0]})),
    ("an unknown error status",
     lambda d: d["fields"][SYNTH_NAME]["variables"]["t2m"]["error"]["status"]
     .update({"24": "probably_fine"})),
    ("an extra key in the encoding block",
     lambda d: d["fields"][SYNTH_NAME]["encoding"].update(gamma=2.2)),
    ("no models at all", lambda d: d["fields"][SYNTH_NAME].update(models=[])),
    ("negative byte total",
     lambda d: d["fields"][SYNTH_NAME].update(bytes=-1)),
    ("resolution of zero",
     lambda d: d["fields"][SYNTH_NAME]["grid"].update(resolution_deg=0)),
]


def tree_self_test(manifest_schema: dict) -> list[str]:
    fails = []
    tmp = Path(tempfile.mkdtemp(prefix="check_fields_"))
    try:
        with contextlib.redirect_stdout(io.StringIO()):
            cfg = _synth_site(tmp)
            base, stats = check_tree(tmp / "data", cfg, manifest_schema,
                                     SYNTH_NOW, _synth_provider)
        if base:
            return ["tree self-test: the pristine synthetic tree does not pass "
                    f"its own checks ({base[0]})"]
        if not stats.get("n_decoded"):
            return ["tree self-test: the pristine tree decoded 0 PNG(s) — the "
                    "half-step gate is not running at all"]
        for desc, corrupt in TREE_CORRUPTIONS:
            work = Path(tempfile.mkdtemp(prefix="check_fields_case_"))
            try:
                with contextlib.redirect_stdout(io.StringIO()):
                    shutil.copytree(tmp, work, dirs_exist_ok=True)
                    corrupt(work)
                    errs, _ = check_tree(work / "data", _synth_cfg_for(work),
                                         manifest_schema, SYNTH_NOW,
                                         _synth_provider)
                if not errs:
                    fails.append(f"tree self-test: {desc!r} was ACCEPTED — the "
                                 "gate is not enforcing this")
            except Exception as e:  # noqa: BLE001
                fails.append(f"tree self-test {desc!r}: raised instead of "
                             f"reporting ({type(e).__name__}: {e})")
            finally:
                shutil.rmtree(work, ignore_errors=True)

        # A real-time init whose truth landed days ago and was never re-exported.
        work = Path(tempfile.mkdtemp(prefix="check_fields_stale_"))
        try:
            with contextlib.redirect_stdout(io.StringIO()):
                shutil.copytree(tmp, work, dirs_exist_ok=True)
                # An init three days old whose first lead's truth landed two
                # days ago, exported once as truth_pending and never revisited.
                # Internally consistent: the PNG is genuinely absent and there
                # is genuinely no scale, so only the clock can reveal it.
                for m in SYNTH_MODELS:
                    _png(work, m, "error", 24).unlink()
                stamp = f"{SYNTH_NOW - timedelta(days=3):{export.TIME_FMT}}"
                _edit(work, lambda e: (
                    e.update(regime="realtime", tier="provisional",
                             init_time=stamp),
                    e["variables"]["t2m"]["error"]["status"].update(
                        {"24": "truth_pending"}),
                    e["variables"]["t2m"]["error"]["scales"].pop("24", None)))
                _refresh_bytes(work)
                errs, _ = check_tree(work / "data", _synth_cfg_for(work),
                                     manifest_schema, SYNTH_NOW, _synth_provider)
            if not any("truth_pending" in e and "available since" in e
                       for e in errs):
                fails.append("tree self-test: a real-time init left three days "
                             "behind its available truth was ACCEPTED — nothing "
                             "would ever make its error map complete")
        finally:
            shutil.rmtree(work, ignore_errors=True)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    return fails


def _synth_cfg_for(site: Path) -> dict:
    return {"paths": {"data": str(site / "store"), "site": str(site)},
            "historic_cutoff_days": 120, "retention_days": 30}


def schema_self_test(manifest_schema: dict) -> list[str]:
    """Every mutation of a valid fields section must be rejected."""
    tmp = Path(tempfile.mkdtemp(prefix="check_fields_schema_"))
    try:
        with contextlib.redirect_stdout(io.StringIO()):
            _synth_site(tmp)
        doc = json.loads((tmp / "data" / "manifest.json").read_text())
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    return check_export.self_test(doc, manifest_schema, FIELD_SCHEMA_MUTATIONS,
                                  "fields")


# ---------------------------------------------------------------------------


def main() -> int:
    import argparse

    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--config", default="config.yaml")
    ap.add_argument("--no-source-check", action="store_true",
                    help="skip layer 3 (needs the forecast zarrs and a truth "
                         "fetch). The self-test still exercises it.")
    a = ap.parse_args()
    repo = Path(__file__).resolve().parents[1]
    cfg = yaml.safe_load((repo / a.config).read_text())
    root = repo / cfg["paths"]["site"] / "data"

    manifest_schema = json.loads(
        (root / "schema" / "manifest.schema.json").read_text())
    check_export.assert_supported(manifest_schema, "manifest")
    print(f"[check] validator: {check_export.VALIDATOR}")

    failures: list[str] = []
    provider = None if a.no_source_check else real_source_provider(cfg)
    tree_failures, stats = check_tree(root, cfg, manifest_schema,
                                      export._utcnow(), provider)
    failures += tree_failures
    if not stats:
        print(f"\n[check] FAILED — {failures[0] if failures else 'no stats'}")
        return 1

    for entry in stats["inits"]:
        n = entry["bytes"]
        grid = entry["grid"]
        print(f"[check] {entry['init_time']}  {entry['regime']:<8} "
              f"tier={entry['tier']:<11} "
              f"{len(entry['models'])}/{len(entry['models_expected'])} model(s)  "
              f"{grid['height']}x{grid['width']} @ {grid['resolution_deg']}°  "
              f"{entry['png_count']}/{entry['png_count_when_complete']} PNG(s)  "
              f"{n / 1048576:.2f} MiB "
              f"({100 * n / FIELDS_BUDGET_BYTES:.0f}% of budget)")
        for var, vmeta in entry["variables"].items():
            for h in entry["leads"]:
                fs = vmeta["forecast"]["scales"].get(str(h))
                es = vmeta["error"]["scales"].get(str(h))
                st = vmeta["error"]["status"].get(str(h))
                fstep = fields.quantization_step(fs) if fs else float("nan")
                estep = fields.quantization_step(es) if es else float("nan")
                print(f"[check]     {var} {h:>4} h  forecast "
                      f"[{fs[0]:.2f}, {fs[1]:.2f}] step {fstep:.4f}  "
                      + (f"error [{es[0]:+.3f}, {es[1]:+.3f}] step {estep:.4f}"
                         if es else f"error {st}"))

    for name, gone in stats["unverified"]:
        print(f"[check] {name}: {len(gone)} model(s) cannot be checked against "
              f"a source array — {gone}. Their forecast zarrs are gone; the "
              "PNGs stay valid but unverifiable.")
    if provider is not None and stats["n_decoded"] == 0:
        failures.append(
            "no PNG was decoded against a source array. Every init's forecast "
            "zarr has been swept, so the half-step encoding gate — the check "
            "that makes this export trustworthy — did not run on any real "
            "data. Re-export an init whose zarr survives, or re-forecast one.")
    print(f"[check] decode gate: {stats['n_decoded']} PNG(s) decoded and "
          f"compared against their source arrays"
          + (" (skipped: --no-source-check)" if provider is None else ""))

    schema_fails = schema_self_test(manifest_schema)
    failures += schema_fails
    print(f"[check] schema self-test: {len(FIELD_SCHEMA_MUTATIONS)} mutations"
          f"{'' if not schema_fails else ' — FAILURES BELOW'}, all rejected as "
          "required")

    tree_fails = tree_self_test(manifest_schema)
    failures += tree_fails
    print(f"[check] gate self-test: {len(TREE_CORRUPTIONS)} corrupted tree(s) + "
          f"1 stale init{'' if not tree_fails else ' — FAILURES BELOW'}, all "
          "caught as required (pristine tree passes)")

    if failures:
        print(f"\n[check] FAILED — {len(failures)} problem(s):")
        for f in failures:
            print(f"  - {f}")
        return 1
    total = sum(stats["bytes"].values())
    print(f"\n[check] OK — {stats['n_png']} PNG(s) across "
          f"{len(stats['inits'])} init(s), {total / 1048576:.2f} MiB total")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
